import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/backend/lib/prisma';
import { hash } from 'bcrypt';
import { Role } from '@prisma/client'; // Import the Role enum generated by Prisma

// Handles POST requests to create a new user/student
export async function POST(req: NextRequest) {
  try {
    // 1. Parse the request body
    const body = await req.json();
    const { id, name, email, password, department } = body;

    // Basic Validation: Ensure required fields are present
    if (!id || !name || !email || !password) {
      return NextResponse.json({ message: 'Missing required fields: ID, Name, Email, or Password.' }, { status: 400 });
    }
    
    // Check if user already exists
    const existingUser = await prisma.user.findUnique({
        where: { email },
    });

    if (existingUser) {
        return NextResponse.json({ message: 'User with this email already exists.' }, { status: 409 });
    }

    // 2. Hash the password for security
    const hashedPassword = await hash(password, 10); // 10 is the salt rounds

    // 3. Create the new user record in the database
    const newUser = await prisma.user.create({
      data: {
        id: id,
        name: name,
        email: email,
        password: hashedPassword,
        department: department,
        role: Role.STUDENT, // Explicitly set the role as STUDENT
        status: 'Registered', // Set a default status from your enum
      },
      // Select fields to return (never return the raw password!)
      select: {
        id: true,
        name: true,
        email: true,
        role: true,
        department: true,
        createdAt: true,
      }
    });

    // 4. Return success response
    return NextResponse.json(
        { message: 'Student registered successfully', user: newUser }, 
        { status: 201 }
    );

  } catch (error) {
    console.error('Registration Error:', error);
    // Return a generic error response for security
    return NextResponse.json(
        { message: 'Internal Server Error during registration.' }, 
        { status: 500 }
    );
  }
}